sudo: required

language: ruby

services:
  - docker
  
before_install:
- uname -a
- docker info
- docker --version
- docker-compose --version
- time docker build .
- time docker run phusion/passenger-ruby22 /bin/bash -c "ruby -e 'count = 0; while(count < 1000000000); count=count+1; end'"
